version: '3'

env:
  aws_account_id: 450285109346
  aws_region: us-east-1
  dolly_v2_12b: "dolly-v2-12b"
  flan_t5_xxl: "flan-t5-xxl"
  mpt_7b_instruct: "mpt-7b-instruct"
  all_minilm_l6_v2: "all-MiniLM-L6-v2"

tasks:
  tar_model:
    desc: Create TAR model
    cmds:
      - |
        for name in ${dolly_v2_12b} ${flan_t5_xxl} ${mpt_7b_instruct} ${all_minilm_l6_v2}; do
          if [[ -z "${name}" ]]; then
            echo "Variable ${name} not set!"
            exit 1
          fi
          echo "Creating TAR model for ${name}"
          cd model/${name}
          rm -rf model.tar.gz
          tar -zcvf model.tar.gz code
          cd ../..
        done

  upload_model:
    desc: Upload TAR model to S3
    cmds:
      - |
        for name in ${dolly_v2_12b} ${flan_t5_xxl} ${mpt_7b_instruct} ${all_minilm_l6_v2}; do
          if [[ -z "${name}" ]]; then
            echo "Variable ${name} not set!"
            exit 1
          fi
          echo "Uploading TAR model for ${name}"
          cd model/${name}
          aws s3 cp model.tar.gz s3://sagemaker-${aws_region}-${aws_account_id}/${name}/model.tar.gz
          cd ../..
        done

  tf_init:
    desc: Initialize Terraform
    cmds:
      - |
        cd infrastructure/terraform
        terraform init

  tf_plan:
    desc: Plan Terraform
    cmds:
      - |
        cd infrastructure/terraform
        terraform plan

  tf_apply:
    desc: Create SageMaker Resources
    cmds:
      - |
        cd infrastructure/terraform
        terraform apply -auto-approve

  tf_destroy:
    desc: Destroy SageMaker Resources
    cmds:
      - |
        cd infrastructure/terraform
        terraform destroy -auto-approve

  # Deploy to ECS Fargate with an ALB target group?
  run_playground:
    desc: Run Playground
    cmds:
      - |
        docker build --tag playground .
        docker run \
          -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
          -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
          -e AWS_DEFAULT_REGION=us-east-1 \
          -p 8501:8501 \
          playground
