version: '3'

env:
  aws_account_id: 450285109346
  aws_region: us-east-1
  model_name: flan-t5-xxl

tasks:
  tar_model:
    desc: Create TAR model
    cmds:
      - |
        cd model
        rm -rf model.tar.gz
        tar -zcvf model.tar.gz code

  upload_model:
    desc: Upload TAR model to S3
    cmds:
      - |
        cd model
        aws s3 cp model.tar.gz s3://sagemaker-${aws_region}-${aws_account_id}/${model_name}/model.tar.gz

  tf_init:
    desc: Initialize Terraform
    cmds:
      - |
        cd infrastructure/terraform
        terraform init

  tf_plan:
    desc: Plan Terraform
    cmds:
      - |
        cd infrastructure/terraform
        terraform plan

  tf_apply:
    desc: Create SageMaker Resources
    cmds:
      - |
        cd infrastructure/terraform
        terraform apply -auto-approve

  tf_destroy:
    desc: Destroy SageMaker Resources
    cmds:
      - |
        cd infrastructure/terraform
        terraform destroy -auto-approve

  # This needs to be dockerized and deployed to ECS Fargate with an ALB target group
  run_playground:
    desc: Run Playground
    cmds:
      - |
        docker build --tag playground .
        docker run \
          -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
          -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
          -e AWS_DEFAULT_REGION=us-east-1 \
          -p 8501:8501 \
          playground
